import {VERSION,DIFFICULTIES,API_BASE} from './config.js';
import {load,save,newProfile,normalize} from './core/storage.js';
import {api} from './core/api.js';
import {modes} from './modes/modes.js';
import {makeQuestion} from './modes/classic.js';
import {countries,searchCountries} from './data/countries.js';

let state=load();let screen='home';let game=null;let dbFilter='All';let dbQuery='';let timer=null;let timeLeft=12;let frozen=false;let audioCtx=null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const rarityOrder=['Common','Rare','Epic','Legend','Mythic','Divine','Transcendent'];
const items={Hint:{price:100,desc:'Remove one wrong answer.'},'Mega Hint':{price:500,desc:'Remove two wrong answers.'},'Double XP':{price:900,desc:'2× XP for this run.'},'Score Boost':{price:1100,desc:'2× score for this run.'},'Second Chance':{price:1400,desc:'Restore one lost life.'},'Lucky Answer':{price:2500,desc:'Guarantees the current answer.'},'Extra Lives':{price:1800,desc:'+2 lives in the current run.'},'Time Freeze':{price:1600,desc:'Freeze the timer for 5 seconds.'},'Coin Magnet':{price:3000,desc:'+50% coins this run.'},'Boss Slayer':{price:5000,desc:'+50% boss damage this battle.'}};
const skins={Explorer:{price:0,xp:1,coins:1,time:0,drop:1},Scout:{price:3000,xp:1.1,coins:1.1,time:1,drop:1.05},Champion:{price:10000,xp:1.25,coins:1.25,time:2,drop:1.15},Mythic:{price:30000,xp:1.5,coins:1.5,time:3,drop:1.35},Divine:{price:100000,xp:2,coins:2,time:5,drop:1.75},Transcendent:{price:500000,xp:3,coins:3,time:8,drop:2.5},'👑 OWNER':{price:0,xp:10001,coins:10001,time:999,drop:11,owner:true}};
const chestPrices={Common:500,Rare:1500,Epic:5000,Legend:15000,Mythic:50000,Divine:200000,Transcendent:5000000};
const achievements=[['first','🌱 First Steps','Finish your first game',p=>p.totalGames>=1,100],['correct10','🎯 Sharpshooter','Answer 10 questions correctly',p=>p.totalCorrect>=10,300],['combo10','🔥 Combo Master','Reach a ×10 combo',p=>p.bestCombo>=10,500],['rich','🪙 Treasure Hunter','Own 10,000 coins',p=>p.coins>=10000,1000],['boss1','👹 Boss Hunter','Defeat a boss',p=>p.bossesDefeated>=1,1000],['boss10','⚔️ Boss Slayer','Defeat 10 bosses',p=>p.bossesDefeated>=10,5000],['daily7','📅 Dedicated','Complete 7 Daily Challenges',p=>p.dailyStreak>=7,2500],['collector','🎁 Collector','Own a Divine or better chest',p=>(p.chests.Divine||0)+(p.chests.Transcendent||0)>=1,3000],['legend','💎 Legendary','Open a Legend+ chest',p=>p.bestChestRarity&&rarityOrder.indexOf(p.bestChestRarity)>=3,5000],['world','🌍 World Traveler','Discover 100 countries',p=>(p.discovered||0)>=100,5000],['nightmare','💀 Nightmare','Finish Nightmare',p=>(p.stats.nightmare||0)>=1,5000],['perfect','✨ Perfect Run','Finish a run with no wrong answers',p=>(p.perfectRuns||0)>=1,5000]];
function ensure(){if(!state.profile){state.profile=newProfile('Player');save(state);}state.profile=normalize(state.profile);return state.profile;}
function sound(kind){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();const f={click:420,hover:520,open:300,close:220,correct:760,wrong:150,warning:110,freeze:360,combo:980,xp:650,coin:560,chest:240,rare:700,legend:900,divine:1200,transcendent:1500,boss:80,damage:180,defeat:55,achievement:1100}[kind]||440;o.frequency.value=f;o.type=kind==='wrong'||kind==='boss'?'sawtooth':'sine';g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.06,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.16);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.18);}catch(e){}}
document.addEventListener('mouseover',e=>{if(e.target.closest('button'))sound('hover')},{passive:true});document.addEventListener('click',e=>{if(e.target.closest('button'))sound('click')});
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function stopTimer(){clearInterval(timer);timer=null}function startTimer(seconds=12){stopTimer();timeLeft=seconds;frozen=false;updateTimer();timer=setInterval(()=>{if(frozen||game?.owner?.god||game?.owner?.timeInfinity)return;timeLeft--;updateTimer();if(timeLeft<=3&&timeLeft>0)sound('warning');if(timeLeft<=0){stopTimer();timeout()}},1000)}function updateTimer(){const el=$('timer');if(el)el.textContent=frozen?'❄️ FROZEN':timeLeft===Infinity?'⏱️ ∞':`⏱️ ${timeLeft}s`}
function go(s){stopTimer();screen=s;render();sound(s==='home'?'close':'open')}
function render(){const p=ensure();$('topName').textContent=p.name;$('topLevel').textContent=p.level;$('topCoins').textContent=p.coins.toLocaleString();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const target=$(screen+'Screen');if(target)target.classList.add('active');if(screen==='home')renderHome();if(screen==='modes')renderModes();if(screen==='profile')renderProfile();if(screen==='shop')renderShop();if(screen==='inventory')renderInventory();if(screen==='countries')renderCountries();if(screen==='leaderboard')renderLeaderboard();if(screen==='achievements')renderAchievements();if(screen==='pvp')renderPvP();if(screen==='rules')renderRules();if(screen==='updates')renderUpdates();if(screen==='about')renderAbout()}
function renderHome(){const p=ensure(),pct=clamp(Math.round((p.xp%1000)/10),0,99);$('profileSummary').innerHTML=`<div class="home-player">👤 <b>${esc(p.name)}</b> · Lv.${p.level} <span class="bar"><i style="width:${pct}%"></i></span> ${pct}% · 🪙 ${p.coins.toLocaleString()}</div>`}
function renderModes(){$('modeGrid').innerHTML=modes.map(m=>`<button class="mode" data-mode="${m.id}">${m.icon} <b>${m.name}</b><small>${m.description}</small></button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>chooseMode(b.dataset.mode))}
function chooseMode(id){if(id==='classic'){go('difficulty');return}if(id==='boss'){startBoss();return}if(id==='daily'){startRun('daily','hard');return}startRun(id,id==='timeAttack'?'normal':'normal')}
function startRun(mode,difficulty='normal'){const count=mode==='endless'?999:10;const p=ensure();const skin=skins[p.equippedSkin]||skins.Explorer;game={mode,difficulty,index:0,score:0,xp:0,coins:0,lives:mode==='suddenDeath'?1:mode==='survival'?5:3,combo:0,perfect:true,questions:Array.from({length:count},()=>makeQuestion(difficulty)),owner:{god:false,timeInfinity:false,infiniteCombo:false,blessing:false},used:{},doubleXP:false,scoreBoost:false,coinMagnet:false,skin,ownerBless:!!skin.owner,timePerQuestion:12+skin.time};goGame()}
function startClassic(d){startRun('classic',d)}function goGame(){screen='game';renderGame();startTimer(game.timePerQuestion||12)}
function renderGame(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('gameScreen').classList.add('active');const q=game.questions[game.index];$('gameTitle').textContent=`${game.mode.toUpperCase()} • ${DIFFICULTIES[game.difficulty]?.name||game.difficulty}`;$('gameProgress').innerHTML=`Question ${game.index+1}/${game.questions.length>=999?'∞':game.questions.length} <span id="timer">⏱️ ${timeLeft}s</span>`;$('gameStats').innerHTML=`❤️ ${game.owner.god?'∞':game.lives} · 🔥 ×${game.combo} · ⭐ ${game.score} · ✨ ${game.xp} · 🪙 ${game.coins}`;$('question').textContent=q.prompt;$('questionValue').textContent=q.value;$('answers').innerHTML=q.options.map(a=>`<button class="answer" data-a="${esc(a)}">${esc(a)}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(b.dataset.a))}
function timeout(){if(!game)return;if(game.owner.god){game.index++;nextQuestion();return}game.perfect=false;game.combo=0;game.lives--;sound('wrong');toast('⏰ Time up!');if(game.lives<=0){finish();return}nextQuestion()}
function answer(a){if(!game)return;const q=game.questions[game.index];if(game.used.skip){game.used.skip=false;applyCorrect(q,true);return}if(a===q.answer)applyCorrect(q,false);else{game.perfect=false;if(game.owner.god){toast('🛡️ God Mode blocked damage');nextQuestion();return}game.combo=0;game.lives--;ensure().totalWrong++;sound('wrong');toast('❌ Wrong!');if(game.lives<=0){finish();return}nextQuestion()}}
function applyCorrect(q,auto){const p=ensure();game.combo++;if(!game.owner.infiniteCombo)game.combo=clamp(game.combo,0,999999);let mult=game.scoreBoost?2:1;let xp=25*mult,coins=10*mult;if(game.doubleXP)xp*=2;if(game.owner.blessing||game.ownerBless){xp*=10;coins*=10}xp*=game.skin.xp;coins*=game.skin.coins;coins*=game.coinMagnet?1.5:1;game.score+=Math.round((100+game.combo*10)*mult);game.xp+=Math.round(xp);game.coins+=Math.round(coins);p.totalCorrect++;p.discovered=Math.min(countries.length,(p.discovered||0)+1);sound('correct');if(game.combo>=3)sound('combo');sound('xp');sound('coin');toast(auto?'🎯 Perfect Answer!':`✅ Correct! +${Math.round(xp)} XP +${Math.round(coins)} Coins`);nextQuestion()}
function nextQuestion(){game.index++;if(game.index>=game.questions.length){finish();return}game.questions[game.index]??=makeQuestion(game.difficulty);renderGame();startTimer(game.timePerQuestion||12)}
function finish(){stopTimer();const p=ensure();p.totalGames++;p.xp+=Math.round(game.xp);p.coins+=Math.round(game.coins);p.bestScore=Math.max(p.bestScore,game.score);p.bestCombo=Math.max(p.bestCombo,game.combo);p.level=Math.max(1,Math.floor(p.xp/1000)+1);p.stats[game.mode]=(p.stats[game.mode]||0)+1;if(game.difficulty==='nightmare'&&game.mode==='classic')p.stats.nightmare=(p.stats.nightmare||0)+1;if(game.perfect)p.perfectRuns=(p.perfectRuns||0)+1;if(game.mode==='daily'){p.dailyStreak=(p.dailyStreak||0)+1;p.lastDaily=new Date().toISOString().slice(0,10)};checkAchievements();save(state);if(state.token)api.progress(state.token,Math.round(game.xp),Math.round(game.coins)).catch(()=>{});screen='result';render();$('result').innerHTML=`<h2>🏆 ${game.mode==='boss'?'Battle':'Run'} Complete</h2><p>⭐ Score <b>${game.score}</b></p><p>✨ XP <b>+${Math.round(game.xp)}</b></p><p>🪙 Coins <b>+${Math.round(game.coins)}</b></p><p>🔥 Best Combo <b>×${game.combo}</b></p><button onclick="goModes()">🎮 Start Game</button><button onclick="goHome()">🏠 Home</button>`}
function use(name){const p=ensure();if(!p.inventory[name]){toast(`No ${name}.`);return false}p.inventory[name]--;game.used[name]=true;save(state);return true}
function useItem(name){if(!game)return toast('Start a game first.');if(name==='Hint'){if(use('Hint')){const q=game.questions[game.index];[...document.querySelectorAll('.answer')].filter(b=>b.dataset.a!==q.answer).slice(0,1).forEach(b=>b.classList.add('removed'))}}else if(name==='Mega Hint'){if(use('Mega Hint')){const q=game.questions[game.index];[...document.querySelectorAll('.answer')].filter(b=>b.dataset.a!==q.answer).slice(0,2).forEach(b=>b.classList.add('removed'))}}else if(name==='Lucky Answer'){if(use(name))applyCorrect(game.questions[game.index],true)}else if(name==='Second Chance'){if(use(name)){game.lives++;toast('❤️ Life restored')}}else if(name==='Extra Lives'){if(use(name)){game.lives+=2;toast('❤️ +2 lives')}}else if(name==='Double XP'){if(use(name))game.doubleXP=true}else if(name==='Score Boost'){if(use(name))game.scoreBoost=true}else if(name==='Coin Magnet'){if(use(name))game.coinMagnet=true}else if(name==='Boss Slayer'){if(use(name))game.bossDamageMult=1.5}else if(name==='Time Freeze'){if(frozen){toast('❄️ Timer is already frozen.');return}if(use(name)){frozen=true;sound('freeze');updateTimer();setTimeout(()=>{frozen=false;updateTimer()},5000)}}renderInventory()}
function renderInventory(){const p=ensure();$('inventoryContent').innerHTML=Object.entries(p.inventory).filter(([,v])=>v>0).map(([k,v])=>`<div class="inv"><span>🎒 <b>${esc(k)}</b><small>x${v}</small></span><button onclick="useItem('${esc(k)}')">Use</button></div>`).join('')||'<p>Inventory empty.</p>'}
function renderShop(){$('shopContent').innerHTML=`<h3>🧰 Items</h3><div class="shop-grid">${Object.entries(items).map(([n,x])=>`<article class="shop-card"><h3>${esc(n)}</h3><p>${x.desc}</p><b>🪙 ${x.price.toLocaleString()}</b><button onclick="buyItem('${esc(n)}')">Buy</button></article>`).join('')}</div><h3>🎨 Skins</h3><div class="shop-grid">${Object.entries(skins).filter(([n])=>n!=='👑 OWNER').map(([n,x])=>`<article class="shop-card"><h3>${n}</h3><p>XP ×${x.xp} · Coins ×${x.coins} · +${x.time}s · Drop ×${x.drop}</p><b>🪙 ${x.price.toLocaleString()}</b><button onclick="buySkin('${esc(n)}')">${ensure().skins[n]?'Equip':'Buy'}</button></article>`).join('')}</div><h3>🎁 Chests</h3><div class="shop-grid">${rarityOrder.map(r=>`<article class="shop-card rarity-${r.toLowerCase()}"><h3>${r}</h3><p>Owned: x${ensure().chests[r]||0}</p><b>🪙 ${chestPrices[r].toLocaleString()}</b><button onclick="buyChest('${r}')">Buy</button><button onclick="openChest('${r}')">Open Owned</button></article>`).join('')}</div>`}
function buyItem(n){const p=ensure(),x=items[n];if(p.coins<x.price)return toast('Not enough coins.');p.coins-=x.price;p.inventory[n]=(p.inventory[n]||0)+1;save(state);sound('coin');renderShop();toast(`Bought ${n}!`)}function buySkin(n){const p=ensure(),x=skins[n];if(!p.skins[n]){if(p.coins<x.price)return toast('Not enough coins.');p.coins-=x.price;p.skins[n]=true}p.equippedSkin=n;save(state);renderShop();toast(`Equipped ${n}!`)}function buyChest(r){const p=ensure(),price=chestPrices[r];if(p.coins<price)return toast('Not enough coins.');p.coins-=price;p.chests[r]=(p.chests[r]||0)+1;save(state);renderShop();toast(`${r} Chest acquired!`)}
function openChest(r){const p=ensure();if(!p.chests[r])return toast('No chest.');p.chests[r]--;const idx=rarityOrder.indexOf(r);let reward;if(r==='Transcendent'||Math.random()<.35)reward=['Lucky Answer','Mega Hint','Double XP','Score Boost','Second Chance'][Math.floor(Math.random()*5)];else if(idx>=4)reward=['Boss Slayer','Time Freeze','Coin Magnet'][Math.floor(Math.random()*3)];else reward=['Hint','Extra Lives','Time Freeze'][Math.floor(Math.random()*3)];p.inventory[reward]=(p.inventory[reward]||0)+1;p.bestChestRarity=r;save(state);sound(idx>=6?'transcendent':idx>=5?'divine':idx>=3?'legend':idx>=2?'rare':'chest');toast(`🎁 ${r} Chest → ${reward}!`);renderShop();checkAchievements()}
function startBoss(){const bosses=[['Goblin Scout','Common',120],['Iron Beast','Rare',250],['Void Tyrant','Epic',500],['Ancient King','Legend',900],['Mythic Dragon','Mythic',1500],['Divine Seraph','Divine',2500]];const b=bosses[Math.floor(Math.random()*bosses.length)],p=ensure(),skin=skins[p.equippedSkin]||skins.Explorer;game={mode:'boss',difficulty:'nightmare',index:0,score:0,xp:0,coins:0,lives:3,combo:0,boss:{name:b[0],rarity:b[1],maxHP:b[2],hp:b[2]},questions:Array.from({length:Math.ceil(b[2]/30)+5},()=>makeQuestion('nightmare')),owner:{god:false,timeInfinity:false,infiniteCombo:false,blessing:false},used:{},skin,bossDamageMult:1};screen='game';renderBoss();startTimer(12+skin.time);sound('boss')}
function renderBoss(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('gameScreen').classList.add('active');const q=game.questions[game.index];$('gameTitle').textContent=`👹 ${game.boss.name} [${game.boss.rarity}]`;$('gameProgress').innerHTML=`Boss Question ${game.index+1}/${game.questions.length} <span id="timer">⏱️ ${timeLeft}s</span>`;$('gameStats').innerHTML=`❤️ ${game.owner.god?'∞':game.lives} · 🔥 ×${game.combo} · 👹 HP ${Math.max(0,game.boss.hp)}/${game.boss.maxHP}`;$('question').textContent=q.prompt;$('questionValue').textContent=q.value;$('answers').innerHTML=q.options.map(a=>`<button class="answer" data-a="${esc(a)}">${esc(a)}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>bossAnswer(b.dataset.a))}
function bossAnswer(a){const q=game.questions[game.index];if(a===q.answer){const dmg=Math.round((30+game.combo*5)*(game.bossDamageMult||1)*(game.skin.owner?10001:1));game.boss.hp-=dmg;game.combo++;game.xp+=35;game.coins+=20;sound('damage');if(game.boss.hp<=0){defeatBoss();return}toast(`⚔️ ${dmg} damage!`)}else{game.combo=0;if(!game.owner.god)game.lives--;sound('wrong');if(game.lives<=0){finish();return}}game.index++;if(game.index>=game.questions.length)game.questions.push(makeQuestion('nightmare'));renderBoss();startTimer(12+game.skin.time)}
function defeatBoss(){stopTimer();const p=ensure(),mult=game.owner.blessing||game.skin.owner?10:1;p.bossesDefeated++;p.xp+=Math.round(game.xp*mult);p.coins+=Math.round(game.coins*mult);const idx=rarityOrder.indexOf(game.boss.rarity),chest=rarityOrder[clamp(idx,0,6)];p.chests[chest]=(p.chests[chest]||0)+1;const special=game.boss.rarity==='Divine'?'Divine Core':game.boss.rarity==='Mythic'?'Mythic Fang':'Boss Token';p.inventory[special]=(p.inventory[special]||0)+1;p.level=Math.floor(p.xp/1000)+1;checkAchievements();save(state);sound('defeat');screen='result';render();$('result').innerHTML=`<h2>👹 BOSS DEFEATED!</h2><p>⚔️ ${esc(game.boss.name)}</p><p>✨ XP +${Math.round(game.xp*mult)}</p><p>🪙 Coins +${Math.round(game.coins*mult)}</p><p>🎁 ${chest} Chest</p><p>💎 ${special}</p><button onclick="startBoss()">👹 Another Boss</button><button onclick="goHome()">🏠 Home</button>`}
function checkAchievements(){const p=ensure();for(const [id,name,desc,fn,reward] of achievements)if(!p.achievements.includes(id)&&fn(p)){p.achievements.push(id);p.coins+=reward;sound('achievement');toast(`🏆 Achievement: ${name} +${reward} coins`)}save(state)}
function renderAchievements(){const p=ensure();$('achievementContent').innerHTML=achievements.map(a=>`<article class="achievement ${p.achievements.includes(a[0])?'unlocked':''}"><h3>${a[1]}</h3><p>${a[2]}</p><b>${p.achievements.includes(a[0])?'✅ Unlocked':'🔒 Locked'} · +${a[4]} 🪙</b></article>`).join('')}
function renderProfile(){const p=ensure();$('profileContent').innerHTML=`<div class="profile-grid"><div>👤 Name<b>${esc(p.name)}</b></div><div>⭐ Level<b>${p.level}</b></div><div>✨ XP<b>${p.xp.toLocaleString()}</b></div><div>🪙 Coins<b>${p.coins.toLocaleString()}</b></div><div>⚔️ Rating<b>${p.rating}</b></div><div>🏆 Wins<b>${p.wins}</b></div><div>💀 Losses<b>${p.losses}</b></div><div>👹 Bosses<b>${p.bossesDefeated}</b></div><div>🎮 Games<b>${p.totalGames}</b></div><div>🎯 Correct<b>${p.totalCorrect}</b></div><div>🏆 Achievements<b>${p.achievements.length}/${achievements.length}</b></div><div>🎨 Skin<b>${esc(p.equippedSkin)}</b></div></div>`}
function renderCountries(){const list=searchCountries(dbQuery,dbFilter);$('countryCount').textContent=list.length;$('countryList').innerHTML=list.map(c=>`<article class="country"><h3>${esc(c.name)}</h3><p>🏛️ ${esc(c.capital)} · 💰 ${esc(c.currency)} · 🌐 ${esc(c.region)}</p><p>👥 Population: ${c.population||'—'} · 📏 Area: ${c.area?Number(c.area).toLocaleString()+' km²':'—'} · 🗣️ Languages: ${esc(c.languages||'—')}</p></article>`).join('')}
async function renderLeaderboard(){if(!$('leaderboard'))return;$('leaderboard').innerHTML='<p>Loading...</p>';try{const d=await api.leaderboard('rating');$('leaderboard').innerHTML=d.rows.map(r=>`<div class="rank">#${r.rank} <b>${esc(r.name)}</b><span>⚔️ ${r.rating}</span></div>`).join('')||'<p>No players yet.</p>'}catch(e){$('leaderboard').innerHTML='<p>Backend offline. Deploy backend to enable global leaderboard.</p>'}}
async function connectAccount(){try{const d=await api.guest(ensure().name);state.token=d.token;state.profile=Object.assign(ensure(),d.user);save(state);toast('🌍 Connected!');render()}catch(e){toast('Backend unavailable. Local profile remains safe.')}}
async function renderPvP(){$('pvpContent').innerHTML='<p>Finding opponent...</p>';try{if(!state.token){const d=await api.guest(ensure().name);state.token=d.token;state.profile=Object.assign(ensure(),d.user);save(state)}const d=await api.pvpMatch(state.token);$('pvpContent').innerHTML=`<h3>⚔️ Opponent Found</h3><p>${esc(d.opponent.name)} · Rating ${d.opponent.rating}</p><button onclick="playPvP('${d.match.id}','${d.opponent.id}')">Fight</button>`}catch(e){$('pvpContent').innerHTML='<p>No opponent available. Connect the backend and create more players first.</p>'}}
window.playPvP=async(matchId,opponentId)=>{try{const me=await api.me(state.token);const won=confirm('OK = you won, Cancel = you lost.');const winner=won?me.user.id:opponentId;await api.pvpResult(state.token,matchId,winner);const p=ensure();if(won){p.wins++;p.rating+=25}else{p.losses++;p.rating=Math.max(0,p.rating-25)}save(state);toast(won?'🏆 Victory!':'💀 Defeat!');go('profile')}catch(e){toast('PvP result failed.')}};
function renderRules(){$('rulesContent').innerHTML='<ul><li>All modes are inside Start Game.</li><li>Classic contains Easy, Normal, Hard, Extreme and Nightmare.</li><li>Classic uses a 12-second timer modified by skins.</li><li>Hard Currency/Region clues add identifying clues so there is only one correct country.</li><li>Extreme adds Population and Area. Nightmare uses every available field.</li><li>Boss difficulty increases both HP and required questions.</li><li>Items are persistent and used from the Item Bar.</li><li>Time Freeze freezes the timer for exactly 5 seconds and cannot stack.</li><li>Profiles are stored locally and migrated from previous versions.</li><li>Online PvP and leaderboard require the V4 backend to be deployed.</li></ul>'}
function renderUpdates(){$('updatesContent').innerHTML='<article><h3>🚀 V4.0 — GLOBAL REBIRTH</h3><ul><li>🧩 Modular ES-module architecture.</li><li>💾 Persistent V4 storage and profile migration.</li><li>🌍 World-ready database, search and continent filters.</li><li>🎮 Classic, Survival, Time Attack, Sudden Death, Endless, Boss and Daily retained inside Start Game.</li><li>🎯 Classic Easy, Normal, Hard, Extreme, Nightmare hierarchy restored.</li><li>⏱️ Classic timer and item/skin interaction.</li><li>👥 Global account foundation.</li><li>⚔️ PvP matchmaking/result API.</li><li>🏆 Global leaderboard API.</li><li>🎁 Persistent Items, Skins and Chest economy.</li><li>👹 Boss progression and exclusive rewards.</li><li>🔊 WebAudio feedback for UI, gameplay, rewards and bosses.</li><li>👑 Owner testing toolkit with O hotkey.</li></ul></article><article><h3>🚀 V3.5</h3><ul><li>Restored Double XP, Score Boost, Second Chance, Lucky Answer and Extra Lives.</li><li>Time Freeze became a 5-second freeze.</li><li>Added rarity-aware sound direction.</li><li>Added Owner testing items and Item Bar usage.</li><li>Added Population, Area and Languages.</li><li>Added Extreme and Nightmare.</li><li>Database search and persistent storage improvements.</li></ul></article><article><h3>🚀 V3.0</h3><ul><li>Added Survival, Time Attack, Sudden Death and Endless.</li><li>Expanded regional coverage.</li><li>More achievements and boss item effects.</li><li>Expanded chest rewards and Transcendent rarity.</li><li>Reworked UI and removed level cap.</li></ul></article><article><h3>🚀 V2.5</h3><ul><li>Added Skins with gameplay bonuses.</li><li>Added Boss Mode and Boss-exclusive items.</li><li>Restored unique Currency and Region Hard questions.</li><li>Added Profile view and Mega Hint.</li><li>Added six original chest rarities.</li></ul></article><article><h3>🚀 V2.0</h3><ul><li>Multiple game modes.</li><li>Achievement System.</li><li>Daily Challenge.</li><li>Chest System and rarity progression.</li><li>Expanded Rank System.</li></ul></article>'}
function renderAbout(){$('version').textContent=VERSION;$('aboutContent').innerHTML='<p>V4.0 is the global infrastructure and gameplay rebirth.</p><p>Frontend: modular ES modules + persistent local storage.</p><p>Backend: Node.js API for accounts, PvP and leaderboard.</p><p>Owner testing: press <b>O</b>.</p>'}
function createOwnerPanel(){if($('ownerOverlay'))return;const d=document.createElement('div');d.id='ownerOverlay';d.innerHTML='<div class="owner-modal"><h2>👑 OWNER PANEL</h2><p>Press O to close.</p><div class="owner-grid"><button onclick="ownerTool(\'infinite\')">⏱️ Time Freeze Ultra</button><button onclick="ownerTool(\'skip\')">⏭️ Question Skip</button><button onclick="ownerTool(\'perfect\')">🎯 Perfect Answer</button><button onclick="ownerTool(\'kill\')">💀 Instant Boss Kill</button><button onclick="ownerTool(\'lives\')">❤️ Infinite Lives</button><button onclick="ownerTool(\'coins\')">💰 Coin Storm</button><button onclick="ownerTool(\'xp\')">⭐ XP Storm</button><button onclick="ownerTool(\'combo\')">🔥 Infinite Combo</button><button onclick="ownerTool(\'knowledge\')">🧠 All Knowledge</button><button onclick="ownerTool(\'god\')">🛡️ God Mode</button><button onclick="ownerTool(\'reset\')">🌍 World Reset</button><button onclick="ownerTool(\'blessing\')">👑 Owner Blessing</button><button onclick="ownerTool(\'skin\')">🎨 Equip Owner Skin</button><button onclick="ownerTool(\'give\')">🎁 Give All Items</button></div><button onclick="d.remove()">Close</button></div>';document.body.appendChild(d)}
window.ownerTool=tool=>{const p=ensure();if(!game&&!['coins','xp','skin','give'].includes(tool))return toast('Start a game first.');if(tool==='infinite'){game.owner.timeInfinity=true;stopTimer();timeLeft=Infinity;updateTimer();toast('⏱️ Timer = ∞')}if(tool==='skip'){game.used.skip=true;toast('⏭️ Next answer counts as correct.')}if(tool==='perfect')applyCorrect(game.questions[game.index],true);if(tool==='kill'&&game.mode==='boss'){game.boss.hp=0;defeatBoss()}if(tool==='lives')game.owner.god=true;if(tool==='coins'){p.coins+=1000000;save(state);toast('+1,000,000 Coins')}if(tool==='xp'){p.xp+=1000000;p.level=Math.floor(p.xp/1000)+1;save(state);toast('+1,000,000 XP')}if(tool==='combo'){game.owner.infiniteCombo=true;game.combo=999999;renderGame()}if(tool==='knowledge'){toast(`🧠 Answer: ${game.questions[game.index].answer}`)}if(tool==='god'){game.owner.god=true;game.owner.timeInfinity=true;game.owner.infiniteCombo=true;toast('🛡️ God Mode active')}if(tool==='reset'){game.questions=Array.from({length:game.questions.length},()=>makeQuestion(game.difficulty));game.index=0;renderGame();toast('🌍 New question set created.')}if(tool==='blessing'){game.owner.blessing=true;toast('👑 +1000% rewards active')}if(tool==='skin'){p.skins['👑 OWNER']=true;p.equippedSkin='👑 OWNER';save(state);if(game)game.skin=skins['👑 OWNER'];toast('👑 Owner Skin equipped');render()}if(tool==='give'){for(const n of Object.keys(items))p.inventory[n]=(p.inventory[n]||0)+99;for(const r of rarityOrder)p.chests[r]=(p.chests[r]||0)+10;p.skins.Transcendent=true;save(state);toast('🎁 All test items granted');render()}};
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='o'){if($('ownerOverlay'))$('ownerOverlay').remove();else createOwnerPanel()}});
window.goHome=()=>go('home');window.goModes=()=>go('modes');window.goProfile=()=>go('profile');window.goShop=()=>go('shop');window.goInventory=()=>go('inventory');window.goCountries=()=>go('countries');window.goLeaderboard=()=>go('leaderboard');window.goPvP=()=>go('pvp');window.goRules=()=>go('rules');window.goUpdates=()=>go('updates');window.goAbout=()=>go('about');window.goAchievements=()=>go('achievements');window.startClassic=startClassic;window.startBoss=startBoss;window.startDailyChallenge=()=>startRun('daily','hard');window.useItem=useItem;window.buyItem=buyItem;window.buySkin=buySkin;window.buyChest=buyChest;window.openChest=openChest;window.searchDB=()=>{dbQuery=$('countrySearch').value;renderCountries()};window.filterDB=x=>{dbFilter=x;renderCountries()};window.createLocalProfile=()=>{const n=$('newName').value.trim();if(!n)return toast('Enter a name');state.profile=newProfile(n);save(state);render();toast('Profile created!')};window.connectAccount=connectAccount;
$('version').textContent=VERSION;render();
