import {VERSION,DIFFICULTIES} from './config.js';
import {load,save,newProfile} from './core/storage.js';
import {api} from './core/api.js';
import {modes} from './modes/modes.js';
import {makeQuestion} from './modes/classic.js';
import {searchCountries,countries} from './data/countries.js';

let state=load(); let screen='home'; let game=null; let dbFilter='All'; let dbQuery='';
const $=id=>document.getElementById(id); const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function ensure(){if(!state.profile){state.profile=newProfile('Player');save(state);} return state.profile;}
function render(){const p=ensure(); $('topName').textContent=p.name;$('topLevel').textContent=p.level;$('topCoins').textContent=p.coins; document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(screen+'Screen').classList.add('active');
  if(screen==='home')$('profileSummary').innerHTML=`<b>👤 ${esc(p.name)}</b> · ⭐ Lv.${p.level} · 🪙 ${p.coins} · 🏆 ${p.rating} rating`;
  if(screen==='modes')renderModes(); if(screen==='profile')renderProfile(); if(screen==='shop')renderShop(); if(screen==='inventory')renderInventory(); if(screen==='countries')renderCountries(); if(screen==='leaderboard')renderLeaderboard();
}
function renderModes(){ $('modeGrid').innerHTML=modes.map(m=>`<button class="mode" data-mode="${m.id}">${m.icon} <b>${m.name}</b><small>${m.description}</small></button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>chooseMode(b.dataset.mode)); }
function chooseMode(id){if(id==='classic'){screen='difficulty';render();return;} if(id==='boss'){toast('Boss Mode is preserved in the V4 architecture and its combat UI is next in the mode module.');startSimple('boss');return;} startSimple(id);}
function startSimple(id){game={mode:id,difficulty:'normal',index:0,score:0,xp:0,coins:0,lives:id==='suddenDeath'?1:3,combo:0,questions:Array.from({length:id==='endless'?999:10},()=>makeQuestion('normal'))};screen='game';renderGame();}
function startClassic(d){game={mode:'classic',difficulty:d,index:0,score:0,xp:0,coins:0,lives:3,combo:0,questions:Array.from({length:10},()=>makeQuestion(d))};screen='game';renderGame();}
function renderGame(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('gameScreen').classList.add('active');const q=game.questions[game.index];$('gameTitle').textContent=`${game.mode.toUpperCase()} • ${DIFFICULTIES[game.difficulty]?.name||'Normal'}`;$('gameProgress').textContent=`Question ${game.index+1}/${game.questions.length>=999?'∞':game.questions.length}`;$('gameStats').textContent=`❤️ ${game.lives} · 🔥 ${game.combo} · ⭐ ${game.score}`;$('question').textContent=q.prompt;$('questionValue').textContent=q.value; $('answers').innerHTML=q.options.map(a=>`<button class="answer" data-a="${esc(a)}">${esc(a)}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(b.dataset.a));}
function answer(a){const q=game.questions[game.index];const p=ensure();if(a===q.answer){game.combo++;game.score+=100+game.combo*10;game.xp+=25;game.coins+=10; p.totalCorrect++; toast('✅ Correct!');}else{game.combo=0;game.lives--;p.totalWrong++;toast('❌ Wrong!');if(game.lives<=0){finish();return;}}game.index++;if(game.index>=game.questions.length||game.mode==='suddenDeath'&&a!==q.answer){finish();return;}game.questions[game.index]??=makeQuestion(game.difficulty);renderGame();}
function finish(){const p=ensure();p.totalGames++;p.xp+=game.xp;p.coins+=game.coins;p.bestScore=Math.max(p.bestScore,game.score);p.bestCombo=Math.max(p.bestCombo,game.combo);p.level=Math.max(1,Math.floor(p.xp/1000)+1);p.stats[game.mode]=(p.stats[game.mode]||0)+1;save(state);if(state.token)api.progress(state.token,game.xp,game.coins).catch(()=>{});screen='result';render();$('result').innerHTML=`<h2>🏆 Run Complete</h2><p>⭐ Score: <b>${game.score}</b></p><p>✨ XP: <b>+${game.xp}</b></p><p>🪙 Coins: <b>+${game.coins}</b></p><button onclick="window.goModes()">🎮 Play Again</button>`;}
function renderProfile(){const p=ensure();$('profileContent').innerHTML=`<div class="profile-grid"><div>👤 Name<b>${esc(p.name)}</b></div><div>⭐ Level<b>${p.level}</b></div><div>✨ XP<b>${p.xp}</b></div><div>🪙 Coins<b>${p.coins}</b></div><div>⚔️ PvP Rating<b>${p.rating}</b></div><div>🏆 Wins<b>${p.wins}</b></div><div>💀 Losses<b>${p.losses}</b></div><div>👹 Bosses<b>${p.bossesDefeated}</b></div></div>`;}
function renderShop(){$('shopContent').innerHTML=['Items','Skins','Chests'].map(x=>`<section><h3>${x}</h3><p>V4.0 persistent shop module ready. Existing V3 inventory is migrated and retained.</p></section>`).join('');}
function renderInventory(){const p=ensure();$('inventoryContent').innerHTML=Object.entries(p.inventory).map(([k,v])=>`<div class="inv"><span>🎒 ${esc(k)}</span><b>x${v}</b><button ${v?'':'disabled'} onclick="useItem('${esc(k)}')">Use</button></div>`).join('');}
function renderCountries(){const list=searchCountries(dbQuery,dbFilter);$('countryCount').textContent=list.length;$('countryList').innerHTML=list.map(c=>`<article class="country"><h3>${esc(c.name)}</h3><p>🏛️ ${esc(c.capital)} · 💰 ${esc(c.currency)} · 🌐 ${esc(c.region)}</p><p>👥 Population: ${c.population||'Data module pending'} · 📏 Area: ${c.area||'Data module pending'} · 🗣️ Languages: ${esc(c.languages)}</p></article>`).join('');}
async function renderLeaderboard(){ $('leaderboard').innerHTML='<p>Loading global leaderboard...</p>';try{const d=await api.leaderboard('rating');$('leaderboard').innerHTML=d.rows.map(r=>`<div class="rank">#${r.rank} <b>${esc(r.name)}</b><span>⚔️ ${r.rating}</span></div>`).join('')||'<p>No global players yet.</p>';}catch(e){$('leaderboard').innerHTML=`<p>Backend offline. Start backend on port 3000 to enable global leaderboard.</p>`;}}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800);}
window.goHome=()=>{screen='home';render()};window.goModes=()=>{screen='modes';render()};window.goProfile=()=>{screen='profile';render()};window.goShop=()=>{screen='shop';render()};window.goInventory=()=>{screen='inventory';render()};window.goCountries=()=>{screen='countries';render()};window.goLeaderboard=()=>{screen='leaderboard';render()};window.goRules=()=>{screen='rules';render()};window.goUpdates=()=>{screen='updates';render()};window.goAbout=()=>{screen='about';render()};window.startClassic=startClassic;window.useItem=name=>{const p=ensure();if(!p.inventory[name])return toast('Item unavailable.');p.inventory[name]--;save(state);renderInventory();toast(`${name} used!`)};window.searchDB=()=>{dbQuery=$('countrySearch').value;renderCountries()};window.filterDB=x=>{dbFilter=x;renderCountries()};window.createLocalProfile=()=>{const n=$('newName').value.trim();if(!n)return toast('Enter a name');state.profile=newProfile(n);save(state);render();toast('Profile created!')};window.connectAccount=async()=>{try{const d=await api.guest(ensure().name);state.token=d.token;state.profile=Object.assign(ensure(),d.user);save(state);render();toast('🌍 Connected to global server!')}catch(e){toast('Backend unavailable')}};
$('version').textContent=VERSION;render();
