import { VERSION, DIFFICULTIES } from './config.js';
import { countries, searchCountries } from './data/registry.js';
import './data/enrichment.js';
import { load, save, newProfile, normalize } from './core/storage.js';
import { ITEMS, SKINS, CHEST_PRICES, RARITIES, ACHIEVEMENTS, RULES, UPDATE_LOG } from './data/content.js';
import { makeQuestion } from './modes/classic.js';
import { sound, startAudio, raritySound } from './systems/audio.js';
import { initOwnerPanel } from './systems/owner.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
let state=load(),screen='home',game=null,timer=null,timeLeft=12,frozenUntil=0,dbFilter='All',dbQuery='';
function profile(){if(!state.profile)state.profile=newProfile('Player');state.profile=normalize(state.profile);const p=state.profile;p.dailyDate??=p.lastDaily||'';p.dailyCompleted??=0;p.bossesDefeated??=0;p.perfectRuns??=0;p.discovered??=0;p.stats.extreme??=0;p.stats.nightmare??=0;return p}
function persist(){save(state)}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function stopTimer(){clearInterval(timer);timer=null}
function startTimer(seconds=12){stopTimer();timeLeft=seconds;frozenUntil=0;updateTimer();timer=setInterval(()=>{if(frozenUntil>Date.now()||game?.owner?.god||game?.owner?.infiniteTime)return;timeLeft--;updateTimer();if(timeLeft<=3&&timeLeft>0)sound('warning');if(timeLeft<=0){stopTimer();timeout()}},1000)}
function updateTimer(){const e=$('timer');if(!e)return;e.textContent=game?.owner?.infiniteTime?'⏱️ ∞':frozenUntil>Date.now()?'❄️ FROZEN':`⏱️ ${timeLeft}s`}
function show(s){stopTimer();screen=s;render();sound(s==='home'?'close':'open')}
function startRun(mode,difficulty='normal'){const p=profile(),skin=SKINS[p.equippedSkin]||SKINS.Explorer,count=mode==='endless'?999:10;game={mode,difficulty,index:0,score:0,xp:0,coins:0,lives:skin.lives||(mode==='survival'?5:mode==='suddenDeath'?1:3),combo:0,perfect:true,questions:Array.from({length:count},()=>makeQuestion(difficulty)),skin,used:{},doubleXP:false,scoreBoost:false,coinMagnet:false,bossDamageMult:1,owner:{god:false,infiniteTime:false,infiniteCombo:false,blessing:false}};showGame()}
function showGame(){screen='game';renderGame();startTimer(12+(game.skin.time||0))}
function startClassic(d){startRun('classic',d)}
function renderGame(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('gameScreen').classList.add('active');const q=game.questions[game.index];$('gameTitle').textContent=`${game.mode.toUpperCase()} • ${DIFFICULTIES[game.difficulty].name}`;$('gameProgress').textContent=`Question ${game.index+1}/${game.questions.length>=999?'∞':game.questions.length}`;$('gameStats').innerHTML=`❤️ ${game.owner.god?'∞':game.lives} · 🔥 ×${game.combo} · ⭐ ${game.score} · ✨ ${game.xp} · 🪙 ${game.coins}`;$('questionType').textContent=q.label;$('question').textContent=q.prompt;$('questionValue').textContent=q.value;$('answers').innerHTML=q.options.map((a,i)=>`<button class="answer" data-index="${i}">${esc(a)}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>game.mode==='boss'?game.answer(q.options[Number(b.dataset.index)]):answer(q.options[Number(b.dataset.index)]));renderItemBar();updateTimer()}
function timeout(){if(!game)return;if(game.owner.god){nextQuestion();return}game.perfect=false;if(!game.owner.infiniteCombo)game.combo=0;game.lives--;sound('wrong');toast('⏰ Time up!');if(game.lives<=0)return finishRun();nextQuestion()}
function answer(value){if(!game)return;const q=game.questions[game.index];if(game.used.skip){game.used.skip=false;correctAnswer(q,true);return}if(value===q.answer)return correctAnswer(q,false);game.perfect=false;if(game.owner.god){toast('🛡️ God Mode blocked the penalty');return nextQuestion()}if(!game.owner.infiniteCombo)game.combo=0;game.lives--;profile().totalWrong++;sound('wrong');toast('❌ Wrong!');if(game.lives<=0)return finishRun();nextQuestion()}
function addRewards(xp,coins){const p=profile(),skin=game.skin,m=game.owner.blessing?10:1,fx=Math.round(xp*skin.xp*m),fc=Math.round(coins*skin.coins*m*(game.coinMagnet?1.5:1));game.xp+=fx;game.coins+=fc;return[fx,fc]}
function correctAnswer(q,automatic=false){const p=profile();game.combo++;if(!game.owner.infiniteCombo)game.combo=Math.min(game.combo,999999);let xp=25,coins=10;if(game.doubleXP)xp*=2;game.score+=Math.round((100+game.combo*10)*(game.scoreBoost?2:1));const[fx,fc]=addRewards(xp,coins);p.totalCorrect++;p.discovered=Math.min(countries.length,(p.discovered||0)+1);sound('correct');if(game.combo>=3)sound('combo');sound('xp');sound('coin');toast(automatic?'🎯 Perfect Answer!':`✅ Correct! +${fx} XP +${fc} Coins`);nextQuestion()}
function nextQuestion(){game.index++;if(game.index>=game.questions.length)return finishRun();game.questions[game.index]??=makeQuestion(game.difficulty);renderGame();startTimer(12+(game.skin.time||0))}
function finishRun(){stopTimer();const p=profile();p.totalGames++;p.xp+=Math.round(game.xp);p.coins+=Math.round(game.coins);p.bestScore=Math.max(p.bestScore,game.score);p.bestCombo=Math.max(p.bestCombo,game.combo);p.level=Math.floor(p.xp/1000)+1;p.stats[game.mode]=(p.stats[game.mode]||0)+1;if(game.mode==='classic'&&game.difficulty==='nightmare')p.stats.nightmare++;if(game.mode==='classic'&&game.difficulty==='extreme')p.stats.extreme++;if(game.perfect)p.perfectRuns++;if(game.mode==='daily'){p.dailyCompleted++;p.dailyStreak++;p.dailyDate=today()}checkAchievements();persist();screen='result';render();renderResult()}
function useItem(name){if(!game)return toast('Start a game first.');const p=profile();if((p.inventory[name]||0)<=0)return toast(`No ${name}.`);if(name==='Time Freeze'&&frozenUntil>Date.now())return toast('❄️ Timer is already frozen.');p.inventory[name]--;persist();const q=game.questions[game.index];if(name==='Hint')removeWrong(1);else if(name==='Mega Hint')removeWrong(2);else if(name==='Lucky Answer')correctAnswer(q,true);else if(name==='Second Chance'){game.lives++;toast('❤️ +1 life')}else if(name==='Extra Lives'){game.lives+=2;toast('❤️ +2 lives')}else if(name==='Double XP'){game.doubleXP=true;toast('✨ Double XP active')}else if(name==='Score Boost'){game.scoreBoost=true;toast('⭐ Score Boost active')}else if(name==='Coin Magnet'){game.coinMagnet=true;toast('🪙 Coin Magnet active')}else if(name==='Boss Slayer'||name==='Boss Damage'){game.bossDamageMult=(game.bossDamageMult||1)*1.5;toast('⚔️ Boss damage boosted')}else if(name==='Boss Token'){p.coins+=500;toast('🪙 +500 coins')}else if(name==='Mythic Fang'){game.bossDamageMult=(game.bossDamageMult||1)*2;toast('🦷 Boss damage ×2')}else if(name==='Divine Core'){p.xp+=1000;p.coins+=1000;p.level=Math.floor(p.xp/1000)+1;toast('💎 +1000 XP +1000 coins')}else if(name==='Time Freeze'){frozenUntil=Date.now()+5000;sound('freeze');updateTimer();setTimeout(updateTimer,5000)}renderGame()}
function removeWrong(n){const q=game.questions[game.index];[...document.querySelectorAll('.answer')].filter((_,i)=>q.options[i]!==q.answer).slice(0,n).forEach(b=>b.classList.add('removed'));toast(n===1?'💡 Hint used':'✨ Mega Hint used')}
function renderItemBar(){const p=profile();$('itemBar').innerHTML=Object.keys(ITEMS).filter(n=>(p.inventory[n]||0)>0).map(n=>`<div class="item-slot"><span>${ITEMS[n].icon} ${esc(n)} <b>x${p.inventory[n]}</b></span><button onclick="window.useItem('${esc(n)}')">Use</button></div>`).join('')||'<span>No items available.</span>'}
function buyItem(n){const p=profile(),x=ITEMS[n];if(x.bossOnly)return toast('Boss-exclusive item.');if(p.coins<x.price)return toast('Not enough coins.');p.coins-=x.price;p.inventory[n]=(p.inventory[n]||0)+1;persist();sound('coin');renderShop()}
function buySkin(n){const p=profile(),x=SKINS[n];if(!p.skins[n]){if(p.coins<x.price)return toast('Not enough coins.');p.coins-=x.price;p.skins[n]=true}p.equippedSkin=n;persist();renderShop();toast(`🎨 ${n} equipped`)}
function buyChest(r){const p=profile(),price=CHEST_PRICES[r];if(p.coins<price)return toast('Not enough coins.');p.coins-=price;p.chests[r]=(p.chests[r]||0)+1;persist();sound('coin');renderShop()}
function openChest(r){const p=profile();if(!(p.chests[r]>0))return toast('No chest.');p.chests[r]--;const i=RARITIES.indexOf(r);const reward=r==='Transcendent'?'Lucky Answer':i>=4?['Boss Slayer','Time Freeze','Coin Magnet','Lucky Answer'][Math.floor(Math.random()*4)]:i>=2?['Mega Hint','Double XP','Score Boost','Second Chance'][Math.floor(Math.random()*4)]:['Hint','Extra Lives','Time Freeze'][Math.floor(Math.random()*3)];p.inventory[reward]=(p.inventory[reward]||0)+1;p.bestChestRarity=r;persist();raritySound(r);toast(`🎁 ${r} Chest → ${reward}`);checkAchievements();renderShop()}
function renderShop(){const p=profile();$('shopBalance').textContent=p.coins.toLocaleString();$('shopItems').innerHTML=Object.entries(ITEMS).filter(([,x])=>!x.bossOnly).map(([n,x])=>`<article class="shop-card"><h3>${x.icon} ${esc(n)}</h3><p>${x.desc}</p><b>🪙 ${x.price.toLocaleString()}</b><button onclick="window.buyItem('${esc(n)}')">Buy</button></article>`).join('');$('skinShop').innerHTML=Object.entries(SKINS).filter(([,x])=>!x.owner).map(([n,x])=>`<article class="shop-card ${x.rarity}"><h3>🎨 ${esc(n)}</h3><p>XP ×${x.xp} · Coins ×${x.coins} · +${x.time}s · Drop ×${x.drop}</p><b>🪙 ${x.price.toLocaleString()}</b><button onclick="window.buySkin('${esc(n)}')">${p.skins[n]?'Equip':'Buy'}</button></article>`).join('');$('chestShop').innerHTML=RARITIES.map(r=>`<article class="shop-card rarity-${r.toLowerCase()}"><h3>🎁 ${r}</h3><p>Owned: x${p.chests[r]||0}</p><b>🪙 ${CHEST_PRICES[r].toLocaleString()}</b><button onclick="window.buyChest('${r}')">Buy</button><button onclick="window.openChest('${r}')">Open</button></article>`).join('')}
function renderInventory(){const p=profile();$('inventoryContent').innerHTML=Object.entries(ITEMS).map(([n,x])=>`<article class="inventory-card"><div><strong>${x.icon} ${esc(n)}</strong><small>${x.desc}</small></div><b>x${p.inventory[n]||0}</b><button onclick="window.useItem('${esc(n)}')" ${game?'':'disabled'}>Use</button></article>`).join('')}
function checkAchievements(){const p=profile();for(const a of ACHIEVEMENTS)if(!p.achievements.includes(a.id)&&a.check(p)){p.achievements.push(a.id);p.coins+=a.reward;sound('achievement');toast(`🏆 ${a.name} +${a.reward} coins`)}persist()}
function renderAchievements(){const p=profile();$('achievementContent').innerHTML=ACHIEVEMENTS.map(a=>`<article class="achievement ${p.achievements.includes(a.id)?'unlocked':''}"><h3>${a.name}</h3><p>${a.desc}</p><b>${p.achievements.includes(a.id)?'✅ Unlocked':'🔒 Locked'} · +${a.reward} 🪙</b></article>`).join('')}
function renderCountries(){const list=searchCountries(dbQuery,dbFilter);$('countryCount').textContent=list.length;$('countryList').innerHTML=list.map(c=>`<article class="country"><h3>${esc(c.name)}</h3><p>🏛️ ${esc(c.capital)} · 💰 ${esc(c.currency)} · 🌐 ${esc(c.region)}</p><p>👥 Population: ${c.population?Number(c.population).toLocaleString():'—'} · 📏 Area: ${c.area?Number(c.area).toLocaleString()+' km²':'—'} · 🗣️ Languages: ${esc(c.languages||'—')}</p></article>`).join('')}
function rank(l){const r=[['Novice',1],['Explorer',5],['Adventurer',10],['Scholar',20],['Master',30],['Grandmaster',40],['Legend',50],['Mythic',60],['Divine',75],['Transcendent',100],['Eternal',150],['Infinite',250]];let x='Novice';for(const[a,b]of r)if(l>=b)x=a;return x}
function renderProfile(){const p=profile(),pct=(p.xp%1000)/10;$('profileContent').innerHTML=`<div class="profile-grid"><div>👤 Name<b>${esc(p.name)}</b></div><div>⭐ Level<b>${p.level}</b></div><div>✨ XP<b>${p.xp.toLocaleString()}</b></div><div>🪙 Coins<b>${p.coins.toLocaleString()}</b></div><div>🏆 Rank<b>${rank(p.level)}</b></div><div>🎮 Games<b>${p.totalGames}</b></div><div>🎯 Correct<b>${p.totalCorrect}</b></div><div>🔥 Best Combo<b>${p.bestCombo}</b></div><div>👹 Bosses<b>${p.bossesDefeated}</b></div><div>🏆 Achievements<b>${p.achievements.length}/${ACHIEVEMENTS.length}</b></div><div>🎨 Skin<b>${esc(p.equippedSkin)}</b></div></div><div class="xp-line">XP Progress <span>${Math.round(pct)}%</span><i style="width:${pct}%"></i></div>`}
function renderHome(){const p=profile(),pct=(p.xp%1000)/10;$('profileSummary').innerHTML=`👤 <b>${esc(p.name)}</b> · Lv.${p.level} <span class="bar"><i style="width:${pct}%"></i></span> ${Math.round(pct)}% · 🪙 ${p.coins.toLocaleString()}`}
function renderModes(){const m=[['classic','🎮','Classic','10 questions • 5 difficulties'],['survival','❤️','Survival','5 lives'],['timeAttack','⏱️','Time Attack','fast timed run'],['suddenDeath','💀','Sudden Death','one mistake ends it'],['endless','♾️','Endless','no fixed limit'],['boss','👹','Bosses','fight a random boss'],['daily','🎯','Daily Challenge','once per day']];$('modeGrid').innerHTML=m.map(([id,ic,n,d])=>`<button class="mode-card" onclick="window.selectMode('${id}')"><h3>${ic} ${n}</h3><p>${d}</p></button>`).join('')}
function renderDifficulty(){const d=[['easy','🟢','Easy','Capital only'],['normal','🟡','Normal','Capital + country'],['hard','🔴','Hard','Capital + country + Currency + Region'],['extreme','🟣','Extreme','Hard + Population + Area'],['nightmare','💀','Nightmare','All available knowledge']];$('difficultyGrid').innerHTML=d.map(([id,ic,n,desc])=>`<button class="difficulty ${id}" onclick="window.startClassic('${id}')">${ic} <b>${n}</b><small>${desc}</small></button>`).join('')}
function renderRules(){$('rulesContent').innerHTML=RULES.map(x=>`<li>${x}</li>`).join('')}
function renderUpdates(){$('updatesContent').innerHTML=UPDATE_LOG.map(u=>`<article class="update-entry"><h3>${u.title}</h3><ul>${u.items.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('')}
function renderResult(){if(!game)return;$('resultContent').innerHTML=`<h2>🏆 Run Complete</h2><p>⭐ Score <b>${game.score}</b></p><p>✨ XP <b>+${game.xp}</b></p><p>🪙 Coins <b>+${game.coins}</b></p><p>🔥 Combo <b>×${game.combo}</b></p><button onclick="window.goModes()">🎮 Start Game</button><button class="secondary" onclick="window.goHome()">🏠 Home</button>`}
function createProfile(){const n=$('newProfile').value.trim();if(!n)return toast('Enter a name.');state.profile=newProfile(n);persist();render();toast('Profile created!')}
function render(){const p=profile();$('topName').textContent=p.name;$('topLevel').textContent=p.level;$('topCoins').textContent=p.coins.toLocaleString();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const t=$(screen+'Screen');if(t)t.classList.add('active');if(screen==='home')renderHome();if(screen==='modes')renderModes();if(screen==='difficulty')renderDifficulty();if(screen==='profile')renderProfile();if(screen==='shop')renderShop();if(screen==='inventory')renderInventory();if(screen==='achievements')renderAchievements();if(screen==='countries')renderCountries();if(screen==='rules')renderRules();if(screen==='updates')renderUpdates();if(screen==='result')renderResult()}
function startBoss(){import('./systems/boss.js').then(({fightBoss})=>fightBoss({makeQuestion,showGame:g=>{game=g;showGame()},toast,sound,finishBoss}))}
function finishBoss(g){stopTimer();if(g.defeat){game=g;screen='result';$('resultContent').innerHTML='<h2>💀 Boss Battle Lost</h2><p>No rewards this time.</p><button onclick="window.selectMode(\'boss\')">👹 Try Again</button><button onclick="window.goHome()">🏠 Home</button>';render();return}const p=profile();p.bossesDefeated++;p.xp+=g.xp;p.coins+=g.coins;p.chests[g.rewardChest]=(p.chests[g.rewardChest]||0)+1;p.inventory[g.specialItem]=(p.inventory[g.specialItem]||0)+1;p.level=Math.floor(p.xp/1000)+1;checkAchievements();persist();game=g;screen='result';$('resultContent').innerHTML=`<h2>👹 BOSS DEFEATED!</h2><p>⚔️ ${esc(g.boss.name)}</p><p>✨ +${g.xp} XP</p><p>🪙 +${g.coins} Coins</p><p>🎁 ${g.rewardChest} Chest</p><p>💎 ${g.specialItem}</p><button onclick="window.selectMode('boss')">👹 Fight Again</button><button onclick="window.goHome()">🏠 Home</button>`;render()}
function goHome(){show('home')}function goModes(){show('modes')}
window.goHome=goHome;window.goModes=goModes;window.openProfileMenu=()=>show('profile');window.openShop=()=>show('shop');window.openInventory=()=>show('inventory');window.openAchievements=()=>show('achievements');window.openCountries=()=>show('countries');window.openRules=()=>show('rules');window.openUpdates=()=>show('updates');window.startGameMenu=goModes;window.selectMode=id=>id==='classic'?show('difficulty'):id==='boss'?startBoss():id==='daily'?(profile().dailyDate===today()?toast('🎯 Daily Challenge already completed today.'):startRun('daily','hard')):startRun(id,'normal');window.startClassic=startClassic;window.useItem=useItem;window.buyItem=buyItem;window.buySkin=buySkin;window.buyChest=buyChest;window.openChest=openChest;window.createProfile=createProfile;window.searchDB=()=>{dbQuery=$('countrySearch').value;renderCountries()};window.filterDB=x=>{dbFilter=x;renderCountries()};
$('version').textContent=VERSION;document.addEventListener('click',startAudio,{once:true});document.addEventListener('mouseover',e=>{if(e.target.closest('button'))sound('hover')},{passive:true});document.addEventListener('click',e=>{if(e.target.closest('button'))sound('click')});window.addEventListener('countryDataReady',()=>{if(screen==='countries')renderCountries()});initOwnerPanel({getGame:()=>game,profile,persist,renderGame,makeQuestion,toast,finishBoss});render();
