import {VERSION,DIFFICULTIES,RANKS} from './config.js';
import {countries,searchCountries} from './data/registry.js';
import {load,save,newProfile,normalize} from './core/storage.js';
import {ITEMS,SKINS,CHEST_PRICES,RARITIES,ACHIEVEMENTS,RULES,UPDATE_LOG,LEVEL_REWARDS,UPGRADES} from './data/content.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state=load(),p=()=>{state.profile=normalize(state.profile||newProfile('Player'));return state.profile},game=null,timer=null,left=12,dbFilter='All',dbQuery='';
const today=()=>new Date().toISOString().slice(0,10);const saveNow=()=>save(state);
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2500)}
function popup(t,b){let e=$('popup');if(!e){e=document.createElement('div');e.id='popup';document.body.appendChild(e)}e.innerHTML=`<div class="popup-card"><h2>${t}</h2>${b}<button onclick="document.getElementById('popup').remove()">Continue</button></div>`}
function stop(){clearInterval(timer)}function rank(){let r=RANKS[0];for(const x of RANKS)if(p().rating>=x.min)r=x;return r}function xpLevel(){p().level=Math.max(1,Math.floor(p().xp/1000)+1)}
function levelRewards(){const q=p();for(const [k,v] of Object.entries(LEVEL_REWARDS)){const n=+k;if(q.level>=n&&!q.levelRewards.includes(n)){q.levelRewards.push(n);q.coins+=v.coins||0;if(v.item)q.inventory[v.item]=(q.inventory[v.item]||0)+1;popup(`📈 LEVEL ${n} UNLOCKED`,`<p>Reward: <b>${(v.coins||0).toLocaleString()} 🪙</b>${v.item?` + <b>${esc(v.item)}</b>`:''}</p>`)}}}
function achievements(){const q=p();for(const a of ACHIEVEMENTS)if(!q.achievements.includes(a.id)&&a.check(q)){q.achievements.push(a.id);q.coins+=a.reward;popup('🏆 ACHIEVEMENT UNLOCKED',`<h3>${a.name}</h3><p>${a.desc}</p><b>+${a.reward.toLocaleString()} 🪙</b>`);toast(`🏆 ${a.name}`)}}
function screen(n){stop();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const e=$(n+'Screen');if(e)e.classList.add('active');if(n==='home')home();if(n==='modes')modes();if(n==='difficulty')difficulty();if(n==='profile')profileView();if(n==='shop')shop();if(n==='inventory')inventory();if(n==='achievements')achievementView();if(n==='countries')countriesView();if(n==='rules')rules();if(n==='updates')updates()}
function home(){const q=p(),r=rank();$('topName').textContent=q.name;$('topLevel').textContent=q.level;$('topCoins').textContent=q.coins.toLocaleString();$('profileSummary').innerHTML=`👤 <b>${esc(q.name)}</b> · Lv.${q.level} · ${r.icon} ${r.name} ${q.rating} · 🪙 ${q.coins.toLocaleString()}`}
function modes(){const a=[['classic','🎮','Classic','Original mode + 5 difficulties'],['survival','❤️','Survival','5 lives'],['timeAttack','⏱️','Time Attack','fast timed run'],['suddenDeath','💀','Sudden Death','one mistake'],['endless','♾️','Endless','no fixed limit'],['boss','👹','Boss','buffed bosses'],['daily','🎯','Daily Challenge','once per day'],['streak','🔥','Streak Mode','wrong = instant loss'],['hardcore','☠️','Hardcore Classic','1 life • no hints • mixed knowledge'],['ranked','🏆','Ranked','10 questions • Elo climb']];$('modeGrid').innerHTML=a.map(x=>`<button class="mode-card" onclick="window.v4Select('${x[0]}')"><h3>${x[1]} ${x[2]}</h3><p>${x[3]}</p></button>`).join('')}
function difficulty(){const a=[['easy','🟢','Easy','Capital'],['normal','🟡','Normal','Capital + Country + Currency'],['hard','🔴','Hard','Currency + Region + Language'],['extreme','🟣','Extreme','Population + Area'],['nightmare','💀','Nightmare','All knowledge']];$('difficultyGrid').innerHTML=a.map(x=>`<button class="difficulty ${x[0]}" onclick="window.v4Start('classic','${x[0]}')">${x[1]} <b>${x[2]}</b><small>${x[3]}</small></button>`).join('')+`<button class="difficulty hardcore" onclick="window.v4Start('hardcore','nightmare')">☠️ <b>Hardcore Classic</b><small>1 life · no hints · diverse questions</small></button>`}
function makeQ(d='normal',forced){const types=DIFFICULTIES[d]?.types||DIFFICULTIES.normal.types;const type=forced||types[Math.floor(Math.random()*types.length)],c=countries[Math.floor(Math.random()*countries.length)];let prompt,value,answer,label=type;if(type==='capital'){prompt=`What is the capital of ${c.name}?`;value=c.name;answer=c.capital;label='Capital'}else if(type==='country'){prompt=`Which country has ${c.capital} as its capital?`;value=c.capital;answer=c.name;label='Country'}else if(type==='currency'){prompt=`What is the currency of ${c.name}?`;value=c.name;answer=c.currency;label='Currency'}else if(type==='region'){prompt=`Which region is ${c.name} in?`;value=`${c.name} • ${c.continent}`;answer=c.region;label='Region'}else if(type==='language'){prompt=`Which language is associated with ${c.name}?`;value=`${c.name} • ${c.region}`;answer=String(c.languages||'Unknown').split(',')[0].trim();label='Language'}else if(type==='population'){prompt=`Which country has this population?`;value=`${Number(c.population||0).toLocaleString()} people • ${c.continent}`;answer=c.name;label='Population'}else if(type==='area'){prompt=`Which country has an area of about ${Number(c.area||0).toLocaleString()} km²?`;value=c.region;answer=c.name;label='Area'}else{prompt=`Which continent is ${c.name} in?`;value=c.name;answer=c.continent;label='Continent'}const vals=countries.filter(x=>x.name!==c.name).map(x=>type==='capital'?x.capital:type==='country'?x.name:type==='currency'?x.currency:type==='region'?x.region:type==='language'?String(x.languages||'Unknown').split(',')[0].trim():type==='continent'?x.continent:x.name);const opts=[answer,...[...new Set(vals.filter(x=>String(x).trim()!==String(answer).trim()))].sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);return{type,label,prompt,value,answer,options:opts,country:c}}
function start(mode,d='normal'){const q=p(),skin=SKINS[q.equippedSkin]||SKINS.Explorer,n=mode==='endless'?999:10;game={mode,d,index:0,score:0,xp:0,coins:0,lives:skin.lives||(mode==='survival'?5:1),combo:0,streak:0,streakBest:0,correct:0,wrong:0,perfect:true,skin,questions:Array.from({length:n},(_,i)=>makeQ(mode==='ranked'?['easy','normal','hard','extreme','nightmare'][Math.floor(i/2)]:d)),ranked:mode==='ranked',boss:null};showGame()}
function showGame(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('gameScreen').classList.add('active');renderGame();const extra=(p().upgrades['Time Core']||0),sec=game.ranked?Math.max(5,12-Math.floor(game.index/2)):game.mode==='timeAttack'?8:12+(game.skin.time||0)+extra;stop();left=sec;$('timer').textContent=`⏱️ ${left}s`;timer=setInterval(()=>{left--;$('timer').textContent=`⏱️ ${left}s`;if(left<=0){stop();answer(null)}},1000)}
function renderGame(){const q=game.questions[game.index],boss=game.boss;$('gameTitle').textContent=game.ranked?`RANKED • ${q.label}`:`${game.mode.toUpperCase()} • ${DIFFICULTIES[game.d]?.name||'BATTLE'}`;$('gameProgress').textContent=boss?`Question ${game.index+1} · 👹 ${boss.name}`:`Question ${game.index+1}/${game.questions.length>=999?'∞':game.questions.length}`;$('gameStats').innerHTML=`❤️ ${game.lives} · 🔥 ×${game.combo} · ⭐ ${game.score} · ✨ ${game.xp} · 🪙 ${game.coins}${boss?` · 👹 HP ${boss.hp.toLocaleString()}/${boss.maxHP.toLocaleString()}`:''}`;$('questionType').textContent=q.label;$('question').textContent=q.prompt;$('questionValue').textContent=q.value;$('answers').innerHTML=q.options.map((x,i)=>`<button class="answer" onclick="window.v4Answer(${i})">${esc(x)}</button>`).join('');$('itemBar').innerHTML=(game.ranked||game.mode==='hardcore'||game.mode==='streak')?'<span>🚫 Items disabled in this mode.</span>':Object.keys(ITEMS).filter(n=>(p().inventory[n]||0)>0&&!ITEMS[n].bossOnly).map(n=>`<div class="item-slot"><span>${ITEMS[n].icon} ${esc(n)} <b>x${p().inventory[n]}</b></span><button onclick="window.v4Use('${esc(n)}')">Use</button></div>`).join('')||'<span>No items.</span>'}
function answer(i){const q=game.questions[game.index],value=i===null?null:q.options[i];if(value===q.answer){game.correct++;game.combo++;game.streak++;game.streakBest=Math.max(game.streakBest,game.streak);game.score+=100+game.combo*10;let xp=25,coins=10;if(game.mode==='streak')xp*=1.25;if(game.ranked)xp*=1.5;game.xp+=Math.round(xp*(game.skin.xp||1));game.coins+=Math.round(coins*(game.skin.coins||1));p().totalCorrect++;discover(q.country);toast(`✅ Correct! +${Math.round(xp)} XP`);next()}else{game.wrong++;game.perfect=false;game.streak=0;if(game.mode==='streak')return end('Streak broken');if(game.ranked||game.mode==='hardcore'||game.mode==='suddenDeath')return end('One mistake ended the run');game.lives--;if(game.lives<=0)return end('No lives remaining');toast('❌ Wrong!');next()}}
function discover(c){if(!c)return;const q=p();if(!q.discoveredCountries.includes(c.name)){q.discoveredCountries.push(c.name);q.discovered=q.discoveredCountries.length;toast(`🌍 Discovered ${c.name}`)}const m=q.countryMastery[c.name]||{correct:0,wrong:0};m.correct++;m.mastery=Math.round(m.correct/(m.correct+m.wrong)*100);q.countryMastery[c.name]=m}
function next(){game.index++;if(game.index>=game.questions.length)return end('Complete');if(game.ranked)game.questions[game.index]=makeQ(['easy','normal','hard','extreme','nightmare'][Math.floor(game.index/2)]);showGame()}
function end(reason){stop();const q=p();q.totalGames++;q.xp+=Math.round(game.xp);q.coins+=Math.round(game.coins);q.bestScore=Math.max(q.bestScore,game.score);q.bestCombo=Math.max(q.bestCombo,game.combo);q.level=Math.floor(q.xp/1000)+1;q.stats[game.mode]=(q.stats[game.mode]||0)+1;if(game.mode==='streak')q.streakBest=Math.max(q.streakBest,game.streakBest);if(game.mode==='hardcore')q.stats.hardcore++;if(game.mode==='classic'&&game.d==='nightmare')q.stats.nightmare++;if(game.mode==='classic'&&game.d==='extreme')q.stats.extreme++;if(game.ranked){const delta=10+game.correct*5-game.wrong*3+(game.correct===10?10:0);q.rating=Math.max(0,q.rating+delta);delta>0?(q.rankedWins++,q.wins++):(q.rankedLosses++,q.losses++);q.rankedQuestions+=10}levelRewards();achievements();saveNow();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('resultScreen').classList.add('active');$('resultContent').innerHTML=`<h2>${game.ranked?'🏆 Ranked Result':'🏆 Run Complete'}</h2><p>${reason}</p><p>⭐ Score <b>${game.score}</b></p><p>✨ XP <b>+${game.xp}</b></p><p>🪙 Coins <b>+${game.coins}</b></p><p>🔥 Best streak <b>×${game.streakBest}</b></p>${game.ranked?`<p>🏆 Rating <b>${q.rating}</b> · ${rank().name}</p>`:''}<button onclick="window.v4Modes()">🎮 Play Again</button><button class="secondary" onclick="window.v4Home()">🏠 Home</button>`}
function use(n){if(!game||game.ranked||game.mode==='hardcore'||game.mode==='streak')return toast('🚫 Items disabled');const q=p();if(!(q.inventory[n]>0))return toast('No item.');q.inventory[n]--;if(n==='Lucky Answer')return answer(game.questions[game.index].options.indexOf(game.questions[game.index].answer));if(n==='Second Chance')game.lives++;if(n==='Extra Lives')game.lives+=2;if(n==='Double XP')game.xp+=25;if(n==='Score Boost')game.score+=100;if(n==='Coin Magnet')game.coins+=15;if(n==='Time Freeze'){stop();setTimeout(()=>showGame(),5000)}if(n==='Hint'||n==='Mega Hint'){const bad=[...document.querySelectorAll('.answer')].filter((_,i)=>game.questions[game.index].options[i]!==game.questions[game.index].answer);bad.slice(0,n==='Hint'?1:2).forEach(x=>x.classList.add('removed'))}if(n==='Streak Shield')game.streakShield=true;saveNow();renderGame()}
function buyItem(n){const x=ITEMS[n],q=p();if(!x||x.bossOnly)return;if(q.coins<x.price)return toast('Not enough coins');q.coins-=x.price;q.inventory[n]=(q.inventory[n]||0)+1;saveNow();shop()}
function buySkin(n){const x=SKINS[n],q=p();if(q.skins[n]){q.equippedSkin=n;saveNow();return shop()}if(q.coins<x.price)return toast('Not enough coins');q.coins-=x.price;q.skins[n]=true;q.equippedSkin=n;saveNow();shop()}
function buyChest(r){const q=p();if(q.coins<CHEST_PRICES[r])return toast('Not enough coins');q.coins-=CHEST_PRICES[r];q.chests[r]=(q.chests[r]||0)+1;saveNow();shop()}
function openChest(r){const q=p();if(!(q.chests[r]>0))return toast('No chest');q.chests[r]--;const pools={Common:['Hint','Extra Lives'],Rare:['Mega Hint','Time Freeze','Double XP'],Epic:['Double XP','Score Boost','Second Chance'],Legend:['Second Chance','Lucky Answer','Coin Magnet'],Mythic:['Boss Damage','Boss Slayer','Lucky Answer'],Divine:['Boss Slayer','Lucky Answer','Streak Shield','Rank Boost'],Transcendent:['Lucky Answer','Boss Slayer','Rank Boost','World Scanner'],Cosmic:['Cosmic Shard','Lucky Answer','Rank Boost','Streak Shield','World Scanner']};const amount=r==='Cosmic'?5:r==='Transcendent'?3:r==='Divine'?2:1;const out=[];for(let i=0;i<amount;i++){const n=pools[r][Math.floor(Math.random()*pools[r].length)];q.inventory[n]=(q.inventory[n]||0)+1;out.push(`${ITEMS[n].icon} ${n}`)}q.bestChestRarity=r;achievements();saveNow();popup(`🎁 ${r} Chest`,out.map(x=>`<p>${x}</p>`).join(''));shop()}
function upgrade(n){const q=p(),x=UPGRADES[n],lv=q.upgrades[n]||0;if(lv>=x.max)return;if(q.coins<Math.round(x.base*Math.pow(x.step,lv)))return toast('Not enough coins');q.coins-=Math.round(x.base*Math.pow(x.step,lv));q.upgrades[n]=lv+1;saveNow();shop()}
function shop(){screen('shop');$('shopBalance').textContent=p().coins.toLocaleString();$('shopItems').innerHTML=Object.entries(ITEMS).filter(([,x])=>!x.bossOnly).map(([n,x])=>`<article class="shop-card"><h3>${x.icon} ${esc(n)}</h3><p>${x.desc}</p><b>🪙 ${x.price.toLocaleString()}</b><button onclick="window.v4BuyItem('${esc(n)}')">Buy</button></article>`).join('');$('skinShop').innerHTML=Object.entries(SKINS).filter(([,x])=>!x.owner).map(([n,x])=>`<article class="shop-card rarity-${x.rarity}"><h3>🎨 ${esc(n)}</h3><p>${x.power} · XP ×${x.xp} · Coins ×${x.coins} · +${x.time}s</p><b>🪙 ${x.price.toLocaleString()}</b><button onclick="window.v4BuySkin('${esc(n)}')">${p().skins[n]?'Equip':'Buy'}</button></article>`).join('');$('chestShop').innerHTML=RARITIES.map(r=>`<article class="shop-card rarity-${r.toLowerCase()}"><h3>🎁 ${r}</h3><p>Owned x${p().chests[r]||0}</p><b>🪙 ${CHEST_PRICES[r].toLocaleString()}</b><button onclick="window.v4BuyChest('${r}')">Buy</button><button onclick="window.v4OpenChest('${r}')">Open</button></article>`).join('');$('upgradeShop').innerHTML=Object.entries(UPGRADES).map(([n,x])=>{const lv=p().upgrades[n]||0,price=Math.round(x.base*Math.pow(x.step,lv));return `<article class="shop-card"><h3>${x.icon} ${n}</h3><p>${x.desc}</p><b>Level ${lv}/${x.max} · 🪙 ${price.toLocaleString()}</b><button onclick="window.v4Upgrade('${esc(n)}')" ${lv>=x.max?'disabled':''}>${lv>=x.max?'MAX':'Upgrade'}</button></article>`}).join('')}
function profileView(){const q=p(),r=rank();$('profileContent').innerHTML=`<div class="profile-grid"><div>👤 Name<b>${esc(q.name)}</b></div><div>📈 Level<b>${q.level}</b></div><div>✨ XP<b>${q.xp.toLocaleString()}</b></div><div>🪙 Coins<b>${q.coins.toLocaleString()}</b></div><div>${r.icon} Rank<b>${r.name}</b></div><div>🏆 Rating<b>${q.rating}</b></div><div>🎮 Games<b>${q.totalGames}</b></div><div>🎯 Correct<b>${q.totalCorrect}</b></div><div>🔥 Best Combo<b>${q.bestCombo}</b></div><div>🔥 Best Streak<b>${q.streakBest}</b></div><div>🌍 Countries<b>${q.discovered}/${countries.length}</b></div><div>🏆 Achievements<b>${q.achievements.length}/${ACHIEVEMENTS.length}</b></div></div>`}
function inventory(){screen('inventory');$('inventoryContent').innerHTML=Object.entries(ITEMS).map(([n,x])=>`<article class="inventory-card"><div><strong>${x.icon} ${esc(n)}</strong><small>${x.desc}</small></div><b>x${p().inventory[n]||0}</b></article>`).join('')}
function achievementView(){screen('achievements');$('achievementContent').innerHTML=ACHIEVEMENTS.map(a=>`<article class="achievement ${p().achievements.includes(a.id)?'unlocked':''}"><h3>${a.name}</h3><p>${a.desc}</p><b>${p().achievements.includes(a.id)?'✅ Unlocked':'🔒 Locked'} · +${a.reward.toLocaleString()} 🪙</b></article>`).join('')}
function countriesView(){screen('countries');const list=searchCountries(dbQuery,dbFilter);$('countryCount').textContent=list.length;$('countryList').innerHTML=list.map(c=>`<article class="country"><h3>${esc(c.name)}</h3><p>🏛️ ${esc(c.capital)} · 💰 ${esc(c.currency)} · 🌐 ${esc(c.region)}</p><p>🌍 ${esc(c.continent)} · 👥 ${c.population?Number(c.population).toLocaleString():'Updating…'} · 📏 ${c.area?Number(c.area).toLocaleString()+' km²':'Updating…'}</p><p>🗣️ ${esc(c.languages||'Updating…')} · Mastery ${p().countryMastery[c.name]?.mastery||0}%</p></article>`).join('')}
function rules(){screen('rules');$('rulesContent').innerHTML=RULES.map(x=>`<li>${x}</li>`).join('')}
function updates(){screen('updates');$('updatesContent').innerHTML=UPDATE_LOG.map(u=>`<article class="update-entry"><h3>${u.title}</h3><ul>${u.items.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('')}
function bossStart(){import('./systems/boss.js').then(({fightBoss})=>fightBoss({makeQuestion:makeQ,showGame:g=>{game=g;showGame()},toast,sound:()=>{},finishBoss:(g)=>{const q=p();if(g.defeat){return popup('💀 BOSS LOST','<p>No rewards this time.</p>')}q.bossesDefeated++;q.xp+=g.xp;q.coins+=g.coins;q.chests[g.rewardChest]=(q.chests[g.rewardChest]||0)+1;q.inventory[g.specialItem]=(q.inventory[g.specialItem]||0)+1;xpLevel();achievements();saveNow();popup('👹 BOSS DEFEATED',`<p>Reward: <b>${g.rewardChest} Chest</b></p><p>Item: <b>${g.specialItem}</b></p>`);screen('home')}}}))}
window.v4Home=()=>screen('home');window.v4Modes=()=>screen('modes');window.v4Select=id=>id==='classic'?screen('difficulty'):id==='boss'?bossStart():id==='daily'?(p().dailyDate===today()?toast('Daily already complete'):start('daily','hard')):start(id,id==='hardcore'?'nightmare':'normal');window.v4Start=start;window.v4Answer=answer;window.v4Use=use;window.v4BuyItem=buyItem;window.v4BuySkin=buySkin;window.v4BuyChest=buyChest;window.v4OpenChest=openChest;window.v4Upgrade=upgrade;
window.goHome=window.v4Home;window.goModes=window.v4Modes;window.startGameMenu=window.v4Modes;window.openProfileMenu=()=>screen('profile');window.openShop=shop;window.openInventory=inventory;window.openAchievements=achievementView;window.openCountries=countriesView;window.openRules=rules;window.openUpdates=updates;window.selectMode=window.v4Select;window.startClassic=d=>start('classic',d);window.useItem=use;window.buyItem=buyItem;window.buySkin=buySkin;window.buyChest=buyChest;window.openChest=openChest;window.createProfile=()=>{const n=$('newProfile').value.trim();if(n){state.profile=newProfile(n);saveNow();screen('profile')}};window.searchDB=()=>{dbQuery=$('countrySearch').value;countriesView()};window.filterDB=x=>{dbFilter=x;countriesView()};
$('version').textContent=VERSION;window.addEventListener('countryDataReady',()=>{if(document.getElementById('countriesScreen')?.classList.contains('active'))countriesView()});home();
