import {SAVE_KEY} from '../config.js';
const blank=()=>({name:'Guest',xp:0,coins:100,level:1,rating:1000,wins:0,losses:0,totalGames:0,totalCorrect:0,totalWrong:0,bestScore:0,bestCombo:0,bossesDefeated:0,discovered:0,perfectRuns:0,dailyStreak:0,lastDaily:null,achievements:[],inventory:{Hint:3,'Mega Hint':1,'Double XP':0,'Score Boost':0,'Second Chance':0,'Lucky Answer':0,'Extra Lives':0,'Time Freeze':0,'Coin Magnet':0,'Boss Slayer':0},skins:{Explorer:true},equippedSkin:'Explorer',chests:{Common:0,Rare:0,Epic:0,Legend:0,Mythic:0,Divine:0,Transcendent:0},stats:{classic:0,survival:0,timeAttack:0,suddenDeath:0,endless:0,boss:0,daily:0,nightmare:0}});
export function normalize(p){const n=Object.assign(blank(),p||{});n.inventory=Object.assign(blank().inventory,p?.inventory||{});n.chests=Object.assign(blank().chests,p?.chests||{});n.skins=Object.assign(blank().skins,p?.skins||{});n.achievements=Array.isArray(p?.achievements)?p.achievements:[];n.stats=Object.assign(blank().stats,p?.stats||{});n.level=Math.max(1,Number(n.level)||1);return n;}
function extract(d){if(!d)return null;if(d.profile)return normalize(d.profile);if(Array.isArray(d.profiles)){const p=d.profiles.find(x=>x.name===d.currentProfile)||d.profiles[0];return p?normalize(p):null;}if(d.name)return normalize(d);return null;}
export function load(){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');const p=extract(d);if(p)return {profile:p,token:d.token||null};}catch(e){console.warn('V4 storage read failed',e)}
 for(const key of ['asia_country_game_v35','asia_country_game_v30','asia_country_game_v25','asia_country_game_v20']){try{const d=JSON.parse(localStorage.getItem(key)||'null');const p=extract(d);if(p)return {profile:p,token:null};}catch(e){}}
 return {profile:null,token:null};}
export function save(state){localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
export function newProfile(name){return normalize({name:String(name||'Player').trim().slice(0,20)||'Player'});}
