import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const DATA_FILE=path.join(__dirname,'data.json');const PORT=Number(process.env.PORT||3000);const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_PRODUCTION';
const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));
function readDB(){try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch{return {users:{},matches:[]}}}function writeDB(db){fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2))}function id(){return crypto.randomUUID()}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return `${salt}:${hash}`}function verifyPassword(password,stored){try{const [salt,hash]=String(stored).split(':');const actual=crypto.scryptSync(String(password),salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(actual,'hex'))}catch{return false}}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid token'})}}
function publicUser(u){return{id:u.id,name:u.name,xp:u.xp,level:u.level,coins:u.coins,rating:u.rating,wins:u.wins,losses:u.losses,profile:u.profile||null}}
function issue(u){return jwt.sign({sub:u.id},JWT_SECRET,{expiresIn:'30d'})}
app.get('/api/health',(req,res)=>res.json({ok:true,version:'4.0.0',accountSyncReady:true}));
app.post('/api/auth/register',(req,res)=>{const db=readDB(),username=String(req.body?.username||'').trim().slice(0,20),password=String(req.body?.password||'');if(username.length<3||password.length<6)return res.status(400).json({error:'Username must be 3+ chars and password 6+ chars'});if(Object.values(db.users).some(u=>u.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'Username already exists'});const uid=id(),u={id:uid,username,name:username,passwordHash:hashPassword(password),xp:0,level:1,coins:100,rating:1000,wins:0,losses:0,profile:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.users[uid]=u;writeDB(db);res.status(201).json({token:issue(u),user:publicUser(u)})});
app.post('/api/auth/login',(req,res)=>{const db=readDB(),username=String(req.body?.username||'').trim(),password=String(req.body?.password||''),u=Object.values(db.users).find(x=>x.username.toLowerCase()===username.toLowerCase());if(!u||!verifyPassword(password,u.passwordHash))return res.status(401).json({error:'Invalid credentials'});u.updatedAt=new Date().toISOString();writeDB(db);res.json({token:issue(u),user:publicUser(u)})});
app.post('/api/auth/guest',(req,res)=>{const db=readDB(),name=String(req.body?.name||'Guest').trim().slice(0,20)||'Guest',uid=id(),u={id:uid,username:`guest_${uid.slice(0,8)}`,name,xp:0,level:1,coins:100,rating:1000,wins:0,losses:0,profile:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.users[uid]=u;writeDB(db);res.json({token:issue(u),user:publicUser(u)})});
app.get('/api/me',auth,(req,res)=>{const db=readDB(),u=db.users[req.user.sub];if(!u)return res.status(404).json({error:'User not found'});res.json({user:publicUser(u)})});
app.get('/api/me/profile',auth,(req,res)=>{const db=readDB(),u=db.users[req.user.sub];if(!u)return res.status(404).json({error:'User not found'});res.json({profile:u.profile||null,user:publicUser(u)})});
app.put('/api/me/profile',auth,(req,res)=>{const db=readDB(),u=db.users[req.user.sub];if(!u)return res.status(404).json({error:'User not found'});u.profile=req.body?.profile||null;const p=u.profile||{};u.xp=Math.max(0,Number(p.xp??u.xp));u.coins=Math.max(0,Number(p.coins??u.coins));u.level=Math.max(1,Number(p.level??Math.floor(u.xp/1000)+1));u.rating=Math.max(0,Number(p.rating??u.rating));u.updatedAt=new Date().toISOString();writeDB(db);res.json({user:publicUser(u)})});
app.post('/api/me/progress',auth,(req,res)=>{const db=readDB(),u=db.users[req.user.sub];if(!u)return res.status(404).json({error:'User not found'});const xp=Math.min(1000000,Math.max(0,Number(req.body?.xp||0))),coins=Math.min(1000000,Math.max(0,Number(req.body?.coins||0)));u.xp+=xp;u.coins+=coins;u.level=Math.max(1,Math.floor(u.xp/1000)+1);u.updatedAt=new Date().toISOString();writeDB(db);res.json({user:publicUser(u)})});
app.get('/api/leaderboard',(req,res)=>{const db=readDB(),metric=['rating','xp','coins','wins'].includes(req.query.metric)?req.query.metric:'rating',limit=Math.min(100,Math.max(1,Number(req.query.limit||50)));const rows=Object.values(db.users).sort((a,b)=>(b[metric]||0)-(a[metric]||0)).slice(0,limit).map((u,i)=>({rank:i+1,...publicUser(u)}));res.json({metric,rows})});
app.post('/api/pvp/match',auth,(req,res)=>{const db=readDB(),me=db.users[req.user.sub];if(!me)return res.status(404).json({error:'User not found'});const opponent=Object.values(db.users).filter(u=>u.id!==me.id).sort((a,b)=>Math.abs(a.rating-me.rating)-Math.abs(b.rating-me.rating))[0];if(!opponent)return res.status(409).json({error:'No opponent available'});const match={id:id(),a:me.id,b:opponent.id,status:'pending',createdAt:new Date().toISOString()};db.matches.push(match);writeDB(db);res.json({match,opponent:publicUser(opponent)})});
app.post('/api/pvp/:matchId/result',auth,(req,res)=>{const db=readDB(),m=db.matches.find(x=>x.id===req.params.matchId);if(!m||(m.a!==req.user.sub&&m.b!==req.user.sub))return res.status(404).json({error:'Match not found'});if(m.status==='finished')return res.status(409).json({error:'Match already finished'});const winner=String(req.body?.winner||'');if(winner!==m.a&&winner!==m.b)return res.status(400).json({error:'Invalid winner'});const loser=winner===m.a?m.b:m.a,w=db.users[winner],l=db.users[loser];w.wins++;l.losses++;w.rating+=25;l.rating=Math.max(0,l.rating-25);m.status='finished';m.winner=winner;m.finishedAt=new Date().toISOString();writeDB(db);res.json({match:m,winner:publicUser(w),loser:publicUser(l)})});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error'})});app.listen(PORT,()=>console.log(`Asia Country Game v4.0 backend listening on ${PORT}`));
